name: deploy
on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - uses: actions/cache@v4
        id: nix-cache
        with:
          path: /tmp/nixcache
          key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
      - if: "steps.nix-cache.outputs.cache-hit == 'true'"
        run: "nix-store --import < /tmp/nixcache"
      - name: Build credential files
        run: |
          mkdir -p ~/.config/sops/age
          echo $SOPS_AGE_SECRET_KEY > ~/.config/sops/age/keys.txt
          chmod 777 ~/.config/sops/age/keys.txt
          ls -la ~/.config/sops/age
          nix develop . --command "./secrets/build.sh"
        env:
          SOPS_AGE_SECRET_KEY: ${{ secrets.SOPS_AGE_SECRET_KEY }}
          SOPS_AGE_KEY_FILE: ~/.config/sops/age/keys.txt
      - name: Debug
        run: |
          ls -la terraform
          ls -la .
      - run: nix develop . --command "bash -c 'cd terraform && terraform init -backend-config=backend.hcl'"
      - run: nix develop . --command "cd terraform && terraform apply -auto-approve"
      - if: "always() && steps.nix-cache.outputs.cache-hit != 'true'"
        run: "nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache"
      - name: Remove credential files
        if: always()
        run: |
          nix develop . --command "./secrets/remove.sh"
          rm -f ~/.config/sops/keys.txt

