name: deploy
on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.SOPS_AGE_SECRET_KEY }}" > ~/.config/sops/age/keys.txt
          chmod 600 ~/.config/sops/age/keys.txt
      - run: nix develop . --command "./secrets/build.sh"
      - run: nix develop . --command "terraform init -backend-config=backend.hcl"
      - run: nix develop . --command "terraform apply -auto-approve"
      - if: always()
        run: |
          nix develop . --command "./secrets/remove.sh"
          rm -f ~/.config/sops/keys.txt

